{{- define "gateway.routeVersion" -}}
{{- $versions := dict 
    "HTTPRoute" "v1"
    "TCPRoute" "v1alpha2"
    "TLSRoute" "v1alpha2"
    "UDPRoute" "v1alpha2"
    "GRPCRoute" "v1alpha2"
-}}
{{- $kind := .kind -}}
{{- if hasKey $versions $kind -}}
{{- index $versions $kind -}}
{{- else -}}
{{- fail (printf "Unsupported route kind: %s. Supported kinds are: HTTPRoute, TCPRoute, TLSRoute, UDPRoute, GRPCRoute" $kind) -}}
{{- end -}}
{{- end -}}

{{- range .Values.listeners }}
{{- $sectionName := .name }}
{{- range .routes }}
---
apiVersion: gateway.networking.k8s.io/{{ include "gateway.routeVersion" . }}
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ template "gateway.fullname" $ }}
      namespace: {{ $.Release.Namespace }}
      sectionName: {{ $sectionName }}
  {{- with .hostnames }}
  hostnames:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
