{{- range .Values.listeners }}
{{- $sectionName := .name }}
{{- $protocol := .protocol }}
{{- range .routes }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: {{ $protocol }}Route
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
    - name: {{ template "gateway.fullname" $ }}
      namespace: {{ $.Release.Namespace }}
      sectionName: {{ $sectionName }}
  {{- with .hostname }}
  hostnames:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- with .rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
