{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fdb-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "fdb-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "update"
      - "patch"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fdb-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "fdb-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "fdb-cluster.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fdb-cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
