nameOverride: ~
fullnameOverride: ~

labels: {}
annotations: {}

# Flink Kubernetes Operator
operator:
  enabled: true

# Auth Proxy
authProxy:
  global:
    publicDB: false
    autoIAMAuthn: false
  serviceAccount: name@project.iam.gserviceaccount.com
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi

# Sources
sources: []
# sources:
#   # Example 1: Cloud SQL with global defaults (private IP, no auto IAM)
#   - name: cake-mysql-stage
#     auth_proxy: cloud_sql
#     driver: mysql
#     instance_uri: bef-cake-sandbox:asia-southeast1:cake-mysql8-stage
#     # Uses global defaults: publicDB: false, autoIAMAuthn: false
#
#   # Example 2: AlloyDB with source-specific overrides (public IP, auto IAM)
#   - name: cake-alloydb-stage
#     auth_proxy: alloydb
#     driver: postgres
#     instance_uri: projects/bef-cake-sandbox/locations/asia-southeast1/clusters/cake-alloydb-stage-cluster/instances/cake-alloydb-stage
#     publicDB: true      # Override global default
#     autoIAMAuthn: true  # Override global default
#
#   # Example 3: Cloud SQL with mixed overrides (private IP, auto IAM)
#   - name: cake-mysql-prod
#     auth_proxy: cloud_sql
#     driver: mysql
#     instance_uri: bef-cake-prod:asia-southeast1:cake-mysql8-prod
#     autoIAMAuthn: true  # Override global default, publicDB uses global default (false)
#
#   # Example 4: Direct connection (no auth proxy)
#   - name: mysql-example
#     host: test.tld
#     port: 3306
#     username: debezium
#     password: dbz
#     # publicDB and autoIAMAuthn not applicable for non-auth_proxy sources

# Sinks
sinks: []
# sinks:
#   - name: doris-cluster
#     fenodes: doris-cluster-fe.doris:8030
#     benodes: doris-cluster-cg.doris:8040
#     jdbc-url: jdbc:mysql://doris-cluster-fe.doris:9030
#     username: flink-cdc
#     password: flink-cdc

image:
  repository: flink
  tag: "1.20"
  digest: ~
  pullPolicy: IfNotPresent
flinkVersion: v1_20
serviceAccount: flink
jobManager:
  replicas: 1
  resource:
    cpu: 0.1
    memory: 1024Mi
  podTemplate: {}
taskManager:
  replicas: 1
  resource:
    cpu: 0.1
    memory: 1024Mi
  podTemplate: {}
ingress: {}
affinity: {}
nodeSelector: {}
tolerations: {}
podLabels: {}
podAnnotations: {}
podSecurityContext: {}
containerSecurityContext: {}
env: []
envFrom: []
persistence:
  data:
    enabled: false
  log:
    enabled: false
objectStore: file:///opt/flink/data
highAvailability:
  enabled: false
global:
  parallelism: 1
  state: running
  upgradeMode: savepoint
  allowNonRestoredState: false
  sourceRef: ~
  sourceConf: {}
  sinkRef: ~
  sinkConf: {}
  tableConf: {}
  singleSink: ~
  extraArgs: []
  flinkConfiguration: {}
sessionJobs: []
# sessionJobs:
#   - name: job-name
#     resetNonce: 0
#     job:
#       sourceType: mysql
#       sourceDatabase: inventory
#       sinkDatabase: inventory_mysql
#       excludingTables: geom
#       sourceRef: mysql-example
#       sinkRef: doris-cluster
#       singleSink: true
#       extraArgs: []
#     flinkConfiguration: {}
