{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heimdall.fullname" . }}-rolebinding
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "heimdall.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "heimdall.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}