{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "heimdall.fullname" . }}-role
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - flink.apache.org
    resources:
      - flinkdeployments
    verbs: ["get", "list", "watch"]
{{- end }}