{{- if .Values.controlPlane.headplane.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
  labels:
    {{- include "tailnet.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 3000
      cookie_secure: true
      cookie_secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa # placeholder only
    headscale:
      url: http://control-plane:8080
      public_url: {{ .Values.controlPlane.url }}
      config_path: /etc/headscale/config.yaml
      config_strict: true
    integration:
      kubernetes:
        enabled: true
        validate_manifest: true
        pod_name: placeholder
    {{- if .Values.controlPlane.headplane.config.oidc.enabled }}
    oidc:
      issuer: {{ .Values.controlPlane.headplane.config.oidc.issuer }}
      disable_api_key_login: true
      token_endpoint_auth_method: client_secret_post
      redirect_uri: {{ .Values.controlPlane.headplane.config.oidc.redirect_uri }}
      client_id: {{ .Values.controlPlane.headplane.config.oidc.client_id }}
      client_secret: placeholder
      headscale_api_key: placeholder
    {{- end }}
{{- end }}
