apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  labels:
    {{- include "tailnet.labels" . | nindent 4 }}
data:
  config.yaml: |
    server_url: {{ .Values.url }}
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: false
    prefixes:
      {{- toYaml .Values.headscale.config.prefixes | nindent 6 }}
    database:
      type: sqlite
      debug: false
      sqlite:
        path: /etc/headscale/db.sqlite
    noise:
      private_key_path: /etc/headscale/noise_private.key
    derp:
      {{- toYaml .Values.headscale.config.derp | nindent 6 }}
    dns:
      {{- toYaml .Values.headscale.config.dns | nindent 6 }}
    {{- if .Values.headscale.config.oidc.enabled }}
    oidc:
      {{- omit .Values.headscale.config.oidc "enabled" | toYaml | nindent 6 }}
    {{- end }}
