{{- if .Values.controlPlane.headplane.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headscale-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: headscale-token
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: headscale-token
subjects:
  - kind: ServiceAccount
    name: headscale-token
roleRef:
  kind: Role
  name: headscale-token
  apiGroup: rbac.authorization.k8s.io
{{- end }}
