apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailnet.fullname" . }}
  labels:
    {{- include "tailnet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: headscale
    port: 8080
    protocol: TCP
    targetPort: 8080
  {{- if .Values.headplane.enabled }}
  - name: headplane
    port: 3000
    protocol: TCP
    targetPort: 3000
  {{- end }}
  selector:
    {{- include "tailnet.selectorLabels" . | nindent 4 }}
