{{- if .Values.relay.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay
  labels:
    {{- include "tailnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tailnet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: relay
  template:
    metadata:
      labels:
        {{- include "tailnet.labels" . | nindent 8 }}
        app.kubernetes.io/component: relay
    spec:
      serviceAccountName: relay
      containers:
      - name: tailscale
        image: "{{ .Values.relay.image.repository }}:{{ .Values.relay.image.tag }}"
        {{- with .Values.relay.image.pullPolicy -}}
        imagePullPolicy: {{ .Values.relay.image.pullPolicy }}
        {{- end }}
        env:
          {{- $extraArgs := list }}
          {{- $extraArgs = append $extraArgs (printf "--login-server=%s" .Values.controlPlane.url) }}
          {{- if .Values.relay.config.advertise_exit_node }}
          {{- $extraArgs = append $extraArgs "--advertise-exit-node" }}
          {{- end }}
          {{- if gt (len $extraArgs) 0 }}
          - name: TS_EXTRA_ARGS
            value: "{{ join " " $extraArgs }}"
          {{- end }}
          {{- if .Values.relay.config.exit_node }}
          - name: TS_EXIT_NODE
            value: "{{ .Values.relay.config.exit_node }}"
          {{- end }}
          {{- if .Values.relay.config.hostname }}
          - name: TS_HOSTNAME
            value: "{{ .Values.relay.config.hostname }}"
          {{- end }}
          {{- if .Values.relay.config.routes }}
          - name: TS_ROUTES
            value: "{{ .Values.relay.config.routes }}"
          {{- end }}
          {{- if .Values.relay.config.firewall_debug }}
          - name: TS_DEBUG_FIREWALL_MODE
            value: "{{ .Values.relay.config.firewall_debug }}"
          {{- end }}
          # Store the state in a k8s secret
          - name: TS_KUBE_SECRET
            value: "tailscale-auth"
          - name: TS_USERSPACE
            value: "true"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
                optional: true
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          {{- with .Values.relay.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.relay.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
{{- end }}
