apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: headscale
  labels:
    {{- include "tailnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  selector:
    matchLabels:
      {{- include "tailnet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: control-plane
  template:
    metadata:
      labels:
        {{- include "tailnet.labels" . | nindent 8 }}
        app.kubernetes.io/component: control-plane
    spec:
      serviceAccountName: headscale
      {{- if .Values.headplane.enabled }}
      shareProcessNamespace: true
      {{- end }}
      containers:
      - name: headscale
        image: "{{ .Values.headscale.image.repository }}:{{ .Values.headscale.image.tag }}"
        {{- with .Values.headscale.image.pullPolicy -}}
        imagePullPolicy: {{ .Values.headscale.image.pullPolicy }}
        {{- end }}
        args:
          - serve
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale/config.yaml
          subPath: config.yaml
        {{- with .Values.headscale.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.headscale.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.headplane.enabled }}
      - name: headplane
        image: "{{ .Values.headplane.image.repository }}:{{ .Values.headplane.image.tag }}"
        {{- with .Values.headplane.image.pullPolicy -}}
        imagePullPolicy: {{ .Values.headplane.image.pullPolicy }}
        {{- end }}
        envFrom:
          - secretRef:
              name: headscale-api-token
          {{- with .Values.headplane.envFrom -}}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        env:
          - name: HEADPLANE_LOAD_ENV_OVERRIDES
            value: 'true'
          - name: 'HEADPLANE_INTEGRATION__KUBERNETES__POD_NAME'
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- with .Values.headplane.env }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale/config.yaml
          subPath: config.yaml
        - name: headplane-config
          mountPath: /etc/headplane/config.yaml
          subPath: config.yaml
      {{- end }}
      volumes:
        - name: headscale-config
          configMap:
            name: headscale-config
        {{- if .Values.headplane.enabled }}
        - name: headplane-config
          configMap:
            name: headplane-config
        {{- end }}
