
{{- if .Values.relay.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-relay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-relay
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - tailscale-auth
  resources:
  - secrets
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-relay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-relay
subjects:
- kind: ServiceAccount
  name: tailscale-relay
{{- end }}
