{{- if .Values.headplane.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headplane.secret.name }}
  {{- with .Values.headplane.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.headplane.secret.oidc.client_secret}}
  HEADPLANE_OIDC__CLIENT_SECRET: {{ .Values.headplane.secret.oidc.client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.headplane.secret.oidc.client_id }}
  HEADPLANE_OIDC__CLIENT_ID: {{ .Values.headplane.secret.oidc.client_id | b64enc | quote }}
  {{- end }}
  {{- if .Values.headplane.secret.oidc.headscale_api_key }}
  HEADPLANE_OIDC__HEADSCALE_API_KEY: {{ .Values.headplane.secret.oidc.headscale_api_key | b64enc | quote }}
  {{- end }}
  {{- if .Values.headplane.secret.server.cookie_secret }}
  HEADPLANE_SERVER__COOKIE_SECRET: {{ .Values.headplane.secret.server.cookie_secret| b64enc | quote }}
  {{- end }}
{{- end }}
