apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: headscale
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "headscale.labels" . | nindent 8 }}
    spec:
      serviceAccountName: headscale
      {{- if .Values.headplane.enabled }}
      shareProcessNamespace: true
      {{- end }}
      containers:
      - name: headscale
        image: "{{ .Values.headscale.image.repository }}:{{ .Values.headscale.image.tag }}"
        {{- with .Values.headscale.image.pullPolicy -}}
        imagePullPolicy: {{ .Values.headscale.image.pullPolicy }}
        {{- end }}
        args:
          - serve
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale/config.yaml
          subPath: config.yaml
        envFrom:
          - secretRef:
              name: {{ .Values.headscale.secret.name }}
      {{- if .Values.headplane.enabled }}
      - name: headplane
        image: "{{ .Values.headplane.image.repository }}:{{ .Values.headplane.image.tag }}"
        {{- with .Values.headplane.image.pullPolicy -}}
        imagePullPolicy: {{ .Values.headplane.image.pullPolicy }}
        {{- end }}
        envFrom:
          - secretRef:
              name: {{ .Values.headplane.secret.name }}
          - secretRef:
              name: headscale-api-token
        env:
        - name: HEADPLANE_LOAD_ENV_OVERRIDES
          value: 'true'
        - name: 'HEADPLANE_INTEGRATION__KUBERNETES__POD_NAME'
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale/config.yaml
          subPath: config.yaml
        - name: headplane-config
          mountPath: /etc/headplane/config.yaml
          subPath: config.yaml
      {{- end }}
      volumes:
        - name: headscale-config
          configMap:
            name: headscale-config
        {{- if .Values.headplane.enabled }}
        - name: headplane-config
          configMap:
            name: headplane-config
        {{- end }}
