apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ template "robustName" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}{{ if .Values.image.digest }}@sha256:{{ .Values.image.digest }}{{ end }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  flinkVersion: {{ .Values.flinkVersion }}
  serviceAccount: {{ default (include "helm-chart.fullname" .) .Values.serviceAccount }}
  restartNonce: {{ default 0 .Values.restartNonce }}
  {{- if .Values.ingress }}
  ingress:
    {{- toYaml .Values.ingress | nindent 4 }}
  {{- end }}
  jobManager:
    replicas: {{ .Values.jobManager.replicas }}
    resource:
      cpu: {{ .Values.jobManager.cpu }}
      memory: {{ .Values.jobManager.memory }}
  taskManager:
    replicas: {{ .Values.taskManager.replicas }}
    resource:
      cpu: {{ .Values.taskManager.cpu }}
      memory: {{ .Values.taskManager.memory }}
  podTemplate:
    {{- if or .Values.podLabels .Values.podAnnotations }}
    metadata:
      {{- if .Values.podLabels }}
      labels:
        {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if or (eq (include "auth_proxy.has_cloud_sql" .) "true") (eq (include "auth_proxy.has_alloydb" .) "true") }}
      initContainers:
      {{- if eq (include "auth_proxy.has_cloud_sql" .) "true" }}
        {{- include "auth_proxy.cloud_sql" . | nindent 8 }}
      {{- end }}
      {{- if eq (include "auth_proxy.has_alloydb" .) "true" }}
        {{- include "auth_proxy.alloydb" . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: flink-main-container
          {{- if .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- range list "data" "log" }}
            - name: flink-{{ . }}
              mountPath: /opt/flink/{{ . }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- if .Values.env | default false }}
              {{- tpl (toYaml .Values.env) . | nindent 12 }}
            {{- end }}
          {{- end }}
      volumes:
      {{- range list "data" "log" }}
        - name: flink-{{ . }}
          {{- $config := index $.Values.persistence . }}
          {{- if $config.enabled }}
          {{- if $config.csi }}
          csi:
            {{- toYaml $config.csi | nindent 12 }}
          {{- else }}
          persistentVolumeClaim:
            claimName: flink-{{ . }}
          {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- end }}
  flinkConfiguration:
    ### Resources limit factor
    kubernetes.jobmanager.cpu.limit-factor: {{ .Values.jobManager.cpuLimitFactor | quote }}
    kubernetes.jobmanager.memory.limit-factor: {{ .Values.jobManager.memoryLimitFactor | quote }}
    kubernetes.taskmanager.cpu.limit-factor: {{ .Values.taskManager.cpuLimitFactor | quote }}
    kubernetes.taskmanager.memory.limit-factor: {{ .Values.taskManager.memoryLimitFactor| quote }}
    ### RocksDB configuration
    {{- if .Values.rocksDB.enabled }}
    state.backend: rocksdb
    state.backend.incremental: true
    {{- else }}
    taskmanager.memory.managed.size: 0 mb
    {{- end }}
    {{- if .Values.highAvailability.enabled }}
    ### Flink high-availability configuration
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.type: kubernetes
    high-availability.storageDir: {{ .Values.objectStore }}/ha
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    ### Flink metrics configuration
    metrics.reporters: prometheus
    metrics.reporter.prometheus.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prometheus.port: {{ .Values.monitoring.port | quote }}
    {{- end }}
    {{- if .Values.global.flinkConfiguration }}
    ### User provided configuration
    # flinkConfiguration must be map of str: str.
    # Iterate through and quote the values, in case they look like integers.
    {{- range $key, $val := .Values.global.flinkConfiguration }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}
