{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        
        gzip on;
        gzip_vary on;
        gzip_min_length 10240;
        gzip_proxied expired no-cache no-store private must-revalidate;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/x-javascript
            application/javascript
            application/xml+rss
            application/json;
        
        server {
            listen 8081;
            server_name _;
            
            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            # Root redirect to show available deployments
            location = / {
                return 200 '<!DOCTYPE html>
<html>
<head>
    <title>Flink Deployments</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #333; }
        ul { list-style-type: none; padding: 0; }
        li { margin: 10px 0; }
        a { color: #0066cc; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .deployment { background: #f5f5f5; padding: 10px; border-left: 4px solid #0066cc; margin: 10px 0; }
    </style>
</head>
<body>
    <h1>Flink Deployments</h1>
    <p>Available Flink UI interfaces:</p>
    {{- range .Values.pipelines }}
    <div class="deployment">
        <strong>{{ .name }}</strong><br>
        <a href="/{{ .name }}/" target="_blank">Open Flink UI</a>
    </div>
    {{- end }}
</body>
</html>';
                add_header Content-Type text/html;
            }
            
            {{- range .Values.pipelines }}
            {{- $metadataName := printf "%s-%d" .name (default 0 .resetNonce | int) }}
            # Route for {{ .name }} pipeline (metadata: {{ $metadataName }})
            location /{{ .name }}/ {
                proxy_pass http://{{ $metadataName }}-rest.{{ $.Release.Namespace }}.svc.cluster.local:8081/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Handle WebSocket connections for Flink UI
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                
                # Increase timeouts for long-running requests
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
                
                # Handle redirects properly
                proxy_redirect http://{{ $metadataName }}-rest.{{ $.Release.Namespace }}.svc.cluster.local:8081/ /{{ .name }}/;
                
                # Fix relative URLs in responses
                sub_filter_once off;
                sub_filter_types *;
                sub_filter 'href="/' 'href="/{{ .name }}/';
                sub_filter 'src="/' 'src="/{{ .name }}/';
                sub_filter 'action="/' 'action="/{{ .name }}/';
                sub_filter "href='/" "href='/{{ .name }}/";
                sub_filter "src='/" "src='/{{ .name }}/";
                sub_filter "action='/" "action='/{{ .name }}/";
            }
            {{- end }}
        }
    }
{{- end }}