{{- if .Values.uiProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      sendfile on;
      keepalive_timeout 65;
      
      server {
        listen 8081;
        server_name _;
        
        # Health check endpoint
        location /health {
          return 200 "healthy\n";
        }
        
        # Root page - route to heimdall if enabled, otherwise show deployment list
        location = / {
          {{- if .Values.heimdall.enabled }}
          proxy_pass http://{{ include "parent.heimdall.fullname" . }}:{{ .Values.heimdall.service.port | default 8080 }}/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          {{- else }}
          add_header Content-Type text/html;
          return 200 '<h1>Flink Deployments</h1>{{- range .Values.pipelines }}{{- $metadataName := printf "%s-%d" .name (default 0 .resetNonce | int) }}<p><a href="/{{ $metadataName }}/">{{ .name }} ({{ $metadataName }})</a></p>{{- end }}';
          {{- end }}
        }
        
        {{- range .Values.pipelines }}
        {{- $metadataName := printf "%s-%d" .name (default 0 .resetNonce | int) }}

        # Route for {{ .name }} pipeline (metadata: {{ $metadataName }})
        location /{{ $metadataName }}/ {
          proxy_pass http://{{ $metadataName }}-rest:8081/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          # Fix redirects to preserve the correct port and subpath  
          proxy_redirect ~^[^:]+://[^/]+(.*)$ /{{ $metadataName }}$1;
        }

        {{- end }}
      }
    }
{{- end }}
