apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "doris-resource-operator.fullname" . }}-controller-manager
  labels:
  {{- include "doris-resource-operator.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "doris-resource-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "doris-resource-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "doris-resource-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "doris-resource-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controllerManager.manager.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- if .Values.controllerManager.manager.resources }}
        resources: 
          {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.controllerManager.manager.securityContext }}
        securityContext:
          {{- toYaml .Values.controllerManager.manager.securityContext | nindent 10 }}
        {{- end }}
      {{- if .Values.controllerManager.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.controllerManager.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "doris-resource-operator.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
