apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "doris-resource-operator.fullname" . }}-manager-role
  labels:
  {{- include "doris-resource-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqldbs
  - mysqls
  - mysqlusers
  - storagevaults
  - catalogs
  - workloadgroups
  - globalvariables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqldbs/finalizers
  - mysqls/finalizers
  - mysqlusers/finalizers
  - storagevaults/finalizers
  - catalogs/finalizers
  - workloadgroups/finalizers
  - globalvariables/finalizers
  verbs:
  - update
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqldbs/status
  - mysqls/status
  - mysqlusers/status
  - storagevaults/status
  - catalogs/status
  - workloadgroups/status
  - globalvariables/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "doris-resource-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "doris-resource-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "doris-resource-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "doris-resource-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
