#!/bin/bash

# Set the script directory path
SCRIPT_DIR=$(dirname "$(realpath "$0")")
PARENT_DIR=$(dirname "$SCRIPT_DIR")
PARENT_CHART_NAME=$(basename "$SCRIPT_DIR")

# Define parent chart values file path
PARENT_VALUES_FILE="$SCRIPT_DIR/values.yaml"

# Remove existing values file if it exists
rm -f "$PARENT_VALUES_FILE"

# Create the parent chart values file with header
cat <<EOF >"$PARENT_VALUES_FILE"
# This file is generated by $(basename "$0").
# It contains the values of the child charts.
# You can modify it manually if you want to change the values of the child charts.
# The values of the child charts are as follows:
EOF

# Get all subdirectories in the charts directory that contain values.yaml
SUBCHARTS=()
for dir in "$SCRIPT_DIR"/charts/*/; do
  if [ -f "$dir/values.yaml" ]; then
    SUBCHARTS+=("$(basename "$dir")")
  fi
done

# Add each subchart's values to the parent values file
for subchart in "${SUBCHARTS[@]}"; do
  echo -e "\n$subchart:" >>"$PARENT_VALUES_FILE"
  # Remove YAML document separators (---) and indent the content
  grep -v "^---$" "$SCRIPT_DIR/charts/$subchart/values.yaml" | awk '{printf("  %s\n", $0);}' >>"$PARENT_VALUES_FILE"
done

echo "Generated parent chart values file: $PARENT_VALUES_FILE"
echo "Included subcharts: ${SUBCHARTS[*]}"
