# Default values for operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dorisOperator:
  # the namespace of dorisoperator, if not set, the release namespace will be used.
  image:
    repository: apache/doris
    tag: operator-latest
    imagePullPolicy: ""
  # ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this deployment.
  # If specified, these secrets will be passed to individual puller implementations for them to use.
  #  imagePullSecret: "my-registry-key"
  # Map of nodeSelectors to match when scheduling pods on nodes
  nodeSelector: {}
    # kubernetes.io/arch: amd64
    # kubernetes.io/os: linux
    # app.kubernetes.node.name: "k8s-node1"

  # node affinity for operator pod scheduling.
  nodeAffinity: {}
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchFields:
  #           - key: metadata.name
  #             operator: In
  #             values:
  #               - target-host-name
  enableWebhook: false
  podSecurityContext:
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - "ALL"
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 2Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
