# Default values for headscale.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

url: https://vpn.example.com
headscale:
  image:
    repository: ghcr.io/juanfont/headscale
    tag: "0.25.1"
  config:
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
      allocation: sequential
    derp:
      server:
        enabled: false
        region_id: 999
        region_code: headscale
        region_name: Headscale Embedded DERP
        stun_listen_addr: 0.0.0.0:3478
        private_key_path: /var/lib/headscale/derp_server_private.key
        automatically_add_embedded_derp_region: true
        ipv4: 1.2.3.4
        ipv6: 2001:db8::1
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
    dns:
      magic_dns: true
      base_domain: headscale.vpn
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8
    oidc:
      issuer: https://your-oidc-issuer.com
      client_id: YOUR_OIDC_CLIENT_ID_FOR_HEADSCALE
  #      allowed_groups:
  #        - vpn_access
  #     allowed_domains:
  #       - example.com
  #     allowed_users:
  #      - alice@example.com
  env: []
  envFrom: []
headplane:
  enabled: true
  image:
    repository: ghcr.io/tale/headplane
    tag: "0.5.10"
  config:
    oidc:
      issuer: https://your-oidc-issuer.com
      disable_api_key_login: true
      token_endpoint_auth_method: client_secret_post
      redirect_uri: https://your-headplane-admin-domain.com/admin/oidc/callback
      client_id: YOUR_OIDC_CLIENT_ID_FOR_HEADPLANE
      client_secret: placeholder
      headscale_api_key: placeholder
  env: []
  envFrom: []
relay:
  enabled: true
  image:
    repository: ghcr.io/tailscale/tailscale
    tag: "v1.82.0"
  config:
    hostname: example.com
    exit_node: example.com
    login_server: https://vpn.example.com
    advertise_exit_node: true
    firewall_debug: false
    routes: 10.0.0.0/8
  env: []
  envFrom: []
service:
  type: ClusterIP
