apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQL
metadata:
  name: {{ template "doris-resource-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "doris-resource-manager.labels" . | nindent 4 }}
spec:
  host: {{ .Values.host }}
  port: {{ .Values.port }}
  authSecret: {{ .Values.authSecret }}
